name: React Native CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run lint  # Ensure you have a linting script in your project
    - run: npm test      # Ensure you have a testing script in your project

  expo_build:
    needs: lint_and_test
    runs-on: ubuntu-latest  # Change to macos-latest if you're building for iOS
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build for Android
      run: |
        npx expo build:android --no-publish --non-interactive
    - name: Build for iOS
      run: |
        npx expo build:ios --no-publish --non-interactive

  # Optionally, you can add steps to publish to the Expo or App Store once the builds are complete
