\name: React Native CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run Linter and Tests
        run: |
          npm run lint
          npm run test
        env:
          CI: true

  android_build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Install Expo CLI
        run: npm install -g eas-cli
      - name: Build for Android
        run: |
          npx eas build --platform android --non-interactive

  ios_build:
    needs: lint_and_test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Install Expo CLI
        run: npm install -g eas-cli
      - name: Build for iOS
        run: |
          npx eas build --platform ios --non-interactive
