name: React Native CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Install Expo CLI
        run: npm install -g eas-cli
      - name: Set EXPO_TOKEN environment variable
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV
      - name: Set Android Keystore Environment Variables (if needed)
        run: |
          echo "EXPO_ANDROID_KEYSTORE_PATH=${{ secrets.EXPO_ANDROID_KEYSTORE_PATH }}" >> $GITHUB_ENV
          echo "EXPO_ANDROID_KEYSTORE_ALIAS=${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}" >> $GITHUB_ENV
          echo "EXPO_ANDROID_KEYSTORE_PASSWORD=${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
      - name: Build for Android
        run: |
          npx eas build --platform android

  ios_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Install Expo CLI
        run: npm install -g eas-cli
      - name: Set EXPO_TOKEN environment variable
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV
      - name: Build for iOS
        run: |
          npx eas build --platform ios
